import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/head/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/app/components/ui/toaster";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Mr. CleanSZ - Project RPL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-5xl mx-auto p-4">
          <Header />
          {children}
          <Toaster />
          <Footer />
        </main>
      </body>
    </html>
  );
}
